export type BrazilRegion = 
  | "sudeste_sp"      // São Paulo - conciso, eficiente
  | "sudeste_mg"      // Minas Gerais - suave, "nós"
  | "sul"             // PR, SC, RS - formal, estruturado
  | "nordeste_norte"  // Nordeste/Norte - caloroso, narrativo
  | "rio"             // Rio de Janeiro - informal controlado
  | "default";        // Padrão neutro

// Mapeamento de cidades/estados para regiões culturais
const cityRegionMap: Record<string, BrazilRegion> = {
  // ========== SÃO PAULO ==========
  "são paulo": "sudeste_sp",
  "sao paulo": "sudeste_sp",
  "campinas": "sudeste_sp",
  "santos": "sudeste_sp",
  "guarulhos": "sudeste_sp",
  "santo andré": "sudeste_sp",
  "osasco": "sudeste_sp",
  "ribeirão preto": "sudeste_sp",
  "sorocaba": "sudeste_sp",
  "são bernardo do campo": "sudeste_sp",
  "são josé dos campos": "sudeste_sp",
  "piracicaba": "sudeste_sp",
  "bauru": "sudeste_sp",
  "jundiaí": "sudeste_sp",
  "mauá": "sudeste_sp",
  "são josé do rio preto": "sudeste_sp",
  "diadema": "sudeste_sp",
  "carapicuíba": "sudeste_sp",
  "mogi das cruzes": "sudeste_sp",
  "franca": "sudeste_sp",
  "itaquaquecetuba": "sudeste_sp",
  "taubaté": "sudeste_sp",
  "suzano": "sudeste_sp",
  "limeira": "sudeste_sp",
  "taboão da serra": "sudeste_sp",
  "sumaré": "sudeste_sp",
  "praia grande": "sudeste_sp",
  "barueri": "sudeste_sp",
  "embu das artes": "sudeste_sp",
  "são vicente": "sudeste_sp",
  "indaiatuba": "sudeste_sp",
  "americana": "sudeste_sp",
  "araraquara": "sudeste_sp",
  "marília": "sudeste_sp",
  "jacareí": "sudeste_sp",
  "presidente prudente": "sudeste_sp",
  "itapevi": "sudeste_sp",
  "cotia": "sudeste_sp",
  "são carlos": "sudeste_sp",
  "hortolândia": "sudeste_sp",
  "rio claro": "sudeste_sp",
  "santa bárbara d'oeste": "sudeste_sp",
  "araçatuba": "sudeste_sp",
  "ferraz de vasconcelos": "sudeste_sp",
  "francisco morato": "sudeste_sp",
  "itapecerica da serra": "sudeste_sp",
  "itu": "sudeste_sp",
  "bragança paulista": "sudeste_sp",
  "pindamonhangaba": "sudeste_sp",
  "atibaia": "sudeste_sp",
  "botucatu": "sudeste_sp",
  "valinhos": "sudeste_sp",
  "guarujá": "sudeste_sp",
  "cubatão": "sudeste_sp",
  "catanduva": "sudeste_sp",
  "assis": "sudeste_sp",
  "ourinhos": "sudeste_sp",
  "votuporanga": "sudeste_sp",
  "birigui": "sudeste_sp",
  "jaú": "sudeste_sp",
  "lins": "sudeste_sp",
  "itapetininga": "sudeste_sp",
  "sertãozinho": "sudeste_sp",
  
  // ========== MINAS GERAIS ==========
  "belo horizonte": "sudeste_mg",
  "uberlândia": "sudeste_mg",
  "juiz de fora": "sudeste_mg",
  "contagem": "sudeste_mg",
  "betim": "sudeste_mg",
  "montes claros": "sudeste_mg",
  "uberaba": "sudeste_mg",
  "governador valadares": "sudeste_mg",
  "ipatinga": "sudeste_mg",
  "ribeirão das neves": "sudeste_mg",
  "sete lagoas": "sudeste_mg",
  "divinópolis": "sudeste_mg",
  "santa luzia": "sudeste_mg",
  "poços de caldas": "sudeste_mg",
  "patos de minas": "sudeste_mg",
  "pouso alegre": "sudeste_mg",
  "teófilo otoni": "sudeste_mg",
  "barbacena": "sudeste_mg",
  "sabará": "sudeste_mg",
  "varginha": "sudeste_mg",
  "conselheiro lafaiete": "sudeste_mg",
  "itabira": "sudeste_mg",
  "araguari": "sudeste_mg",
  "ubá": "sudeste_mg",
  "passos": "sudeste_mg",
  "coronel fabriciano": "sudeste_mg",
  "muriaé": "sudeste_mg",
  "ituiutaba": "sudeste_mg",
  "lavras": "sudeste_mg",
  "nova lima": "sudeste_mg",
  "araxá": "sudeste_mg",
  "caratinga": "sudeste_mg",
  "patrocínio": "sudeste_mg",
  "itajubá": "sudeste_mg",
  "formiga": "sudeste_mg",
  "ouro preto": "sudeste_mg",
  "são joão del rei": "sudeste_mg",
  "alfenas": "sudeste_mg",
  "três corações": "sudeste_mg",
  "leopoldina": "sudeste_mg",
  "cataguases": "sudeste_mg",
  "frutal": "sudeste_mg",
  "pedro leopoldo": "sudeste_mg",
  "lagoa santa": "sudeste_mg",
  "congonhas": "sudeste_mg",
  "timóteo": "sudeste_mg",
  "mariana": "sudeste_mg",
  "viçosa": "sudeste_mg",
  "diamantina": "sudeste_mg",
  "tiradentes": "sudeste_mg",
  
  // ========== SUL - PARANÁ ==========
  "curitiba": "sul",
  "londrina": "sul",
  "maringá": "sul",
  "ponta grossa": "sul",
  "cascavel": "sul",
  "foz do iguaçu": "sul",
  "são josé dos pinhais": "sul",
  "colombo": "sul",
  "guarapuava": "sul",
  "paranaguá": "sul",
  "apucarana": "sul",
  "toledo": "sul",
  "araucária": "sul",
  "campo largo": "sul",
  "pinhais": "sul",
  "umuarama": "sul",
  "arapongas": "sul",
  "almirante tamandaré": "sul",
  "piraquara": "sul",
  "cambé": "sul",
  "francisco beltrão": "sul",
  "fazenda rio grande": "sul",
  "campo mourão": "sul",
  "sarandi": "sul",
  "paranavaí": "sul",
  "irati": "sul",
  "pato branco": "sul",
  "cianorte": "sul",
  "telêmaco borba": "sul",
  "castro": "sul",
  "rolândia": "sul",
  "união da vitória": "sul",
  
  // ========== SUL - SANTA CATARINA ==========
  "florianópolis": "sul",
  "joinville": "sul",
  "blumenau": "sul",
  "são josé": "sul",
  "chapecó": "sul",
  "criciúma": "sul",
  "itajaí": "sul",
  "jaraguá do sul": "sul",
  "lages": "sul",
  "palhoça": "sul",
  "balneário camboriú": "sul",
  "brusque": "sul",
  "tubarão": "sul",
  "são bento do sul": "sul",
  "caçador": "sul",
  "concórdia": "sul",
  "camboriú": "sul",
  "navegantes": "sul",
  "rio do sul": "sul",
  "biguaçu": "sul",
  "gaspar": "sul",
  "mafra": "sul",
  "araranguá": "sul",
  "indaial": "sul",
  "içara": "sul",
  "canoinhas": "sul",
  "laguna": "sul",
  "videira": "sul",
  "joaçaba": "sul",
  "xanxerê": "sul",
  "imbituba": "sul",
  "garopaba": "sul",
  "bombinhas": "sul",
  "porto belo": "sul",
  
  // ========== SUL - RIO GRANDE DO SUL ==========
  "porto alegre": "sul",
  "caxias do sul": "sul",
  "pelotas": "sul",
  "canoas": "sul",
  "santa maria": "sul",
  "gravataí": "sul",
  "viamão": "sul",
  "novo hamburgo": "sul",
  "são leopoldo": "sul",
  "rio grande": "sul",
  "alvorada": "sul",
  "passo fundo": "sul",
  "sapucaia do sul": "sul",
  "uruguaiana": "sul",
  "santa cruz do sul": "sul",
  "cachoeirinha": "sul",
  "bagé": "sul",
  "bento gonçalves": "sul",
  "erechim": "sul",
  "guaíba": "sul",
  "cachoeira do sul": "sul",
  "santana do livramento": "sul",
  "esteio": "sul",
  "ijuí": "sul",
  "alegrete": "sul",
  "são borja": "sul",
  "lajeado": "sul",
  "sapiranga": "sul",
  "cruz alta": "sul",
  "vacaria": "sul",
  "santo ângelo": "sul",
  "carazinho": "sul",
  "venâncio aires": "sul",
  "farroupilha": "sul",
  "torres": "sul",
  "tramandaí": "sul",
  "capão da canoa": "sul",
  "gramado": "sul",
  "canela": "sul",
  "carlos barbosa": "sul",
  "garibaldi": "sul",
  
  // ========== RIO DE JANEIRO ==========
  "rio de janeiro": "rio",
  "niterói": "rio",
  "são gonçalo": "rio",
  "duque de caxias": "rio",
  "nova iguaçu": "rio",
  "belford roxo": "rio",
  "petrópolis": "rio",
  "volta redonda": "rio",
  "campos dos goytacazes": "rio",
  "são joão de meriti": "rio",
  "magé": "rio",
  "itaboraí": "rio",
  "mesquita": "rio",
  "nova friburgo": "rio",
  "barra mansa": "rio",
  "macaé": "rio",
  "cabo frio": "rio",
  "teresópolis": "rio",
  "nilópolis": "rio",
  "resende": "rio",
  "maricá": "rio",
  "queimados": "rio",
  "angra dos reis": "rio",
  "rio das ostras": "rio",
  "japeri": "rio",
  "itaguaí": "rio",
  "araruama": "rio",
  "três rios": "rio",
  "valença rj": "rio",
  "búzios": "rio",
  "paraty": "rio",
  "saquarema": "rio",
  "miguel pereira": "rio",
  "penedo rj": "rio",
  "visconde de mauá": "rio",
  
  // ========== NORDESTE - BAHIA ==========
  "salvador": "nordeste_norte",
  "feira de santana": "nordeste_norte",
  "vitória da conquista": "nordeste_norte",
  "camaçari": "nordeste_norte",
  "itabuna": "nordeste_norte",
  "juazeiro": "nordeste_norte",
  "lauro de freitas": "nordeste_norte",
  "ilhéus": "nordeste_norte",
  "jequié": "nordeste_norte",
  "teixeira de freitas": "nordeste_norte",
  "barreiras": "nordeste_norte",
  "alagoinhas": "nordeste_norte",
  "porto seguro": "nordeste_norte",
  "simões filho": "nordeste_norte",
  "paulo afonso": "nordeste_norte",
  "eunápolis": "nordeste_norte",
  "santo antônio de jesus": "nordeste_norte",
  "valença ba": "nordeste_norte",
  "candeias": "nordeste_norte",
  "guanambi": "nordeste_norte",
  "jacobina": "nordeste_norte",
  "serrinha": "nordeste_norte",
  "senhor do bonfim": "nordeste_norte",
  "cruz das almas": "nordeste_norte",
  "itamaraju": "nordeste_norte",
  "itapetinga": "nordeste_norte",
  "luís eduardo magalhães": "nordeste_norte",
  "morro de são paulo": "nordeste_norte",
  "lençóis": "nordeste_norte",
  "trancoso": "nordeste_norte",
  "arraial d'ajuda": "nordeste_norte",
  
  // ========== NORDESTE - PERNAMBUCO ==========
  "recife": "nordeste_norte",
  "jaboatão dos guararapes": "nordeste_norte",
  "olinda": "nordeste_norte",
  "caruaru": "nordeste_norte",
  "petrolina": "nordeste_norte",
  "paulista": "nordeste_norte",
  "cabo de santo agostinho": "nordeste_norte",
  "camaragibe": "nordeste_norte",
  "garanhuns": "nordeste_norte",
  "vitória de santo antão": "nordeste_norte",
  "igarassu": "nordeste_norte",
  "são lourenço da mata": "nordeste_norte",
  "abreu e lima": "nordeste_norte",
  "serra talhada": "nordeste_norte",
  "araripina": "nordeste_norte",
  "gravatá": "nordeste_norte",
  "carpina": "nordeste_norte",
  "goiana": "nordeste_norte",
  "belo jardim": "nordeste_norte",
  "arcoverde": "nordeste_norte",
  "porto de galinhas": "nordeste_norte",
  "fernando de noronha": "nordeste_norte",
  
  // ========== NORDESTE - CEARÁ ==========
  "fortaleza": "nordeste_norte",
  "caucaia": "nordeste_norte",
  "juazeiro do norte": "nordeste_norte",
  "maracanaú": "nordeste_norte",
  "sobral": "nordeste_norte",
  "crato": "nordeste_norte",
  "itapipoca": "nordeste_norte",
  "maranguape": "nordeste_norte",
  "iguatu": "nordeste_norte",
  "quixadá": "nordeste_norte",
  "pacatuba": "nordeste_norte",
  "aquiraz": "nordeste_norte",
  "russas": "nordeste_norte",
  "canindé": "nordeste_norte",
  "tianguá": "nordeste_norte",
  "aracati": "nordeste_norte",
  "crateús": "nordeste_norte",
  "icó": "nordeste_norte",
  "limoeiro do norte": "nordeste_norte",
  "pacajus": "nordeste_norte",
  "jericoacoara": "nordeste_norte",
  "canoa quebrada": "nordeste_norte",
  "cumbuco": "nordeste_norte",
  
  // ========== NORDESTE - RIO GRANDE DO NORTE ==========
  "natal": "nordeste_norte",
  "mossoró": "nordeste_norte",
  "parnamirim": "nordeste_norte",
  "são gonçalo do amarante": "nordeste_norte",
  "ceará-mirim": "nordeste_norte",
  "macaíba": "nordeste_norte",
  "caicó": "nordeste_norte",
  "assu": "nordeste_norte",
  "currais novos": "nordeste_norte",
  "são josé de mipibu": "nordeste_norte",
  "joão câmara": "nordeste_norte",
  "santa cruz": "nordeste_norte",
  "nova cruz": "nordeste_norte",
  "pau dos ferros": "nordeste_norte",
  "pipa": "nordeste_norte",
  "galinhos": "nordeste_norte",
  "são miguel do gostoso": "nordeste_norte",
  "touros": "nordeste_norte",
  
  // ========== NORDESTE - PARAÍBA ==========
  "joão pessoa": "nordeste_norte",
  "campina grande": "nordeste_norte",
  "santa rita": "nordeste_norte",
  "patos": "nordeste_norte",
  "bayeux": "nordeste_norte",
  "cabedelo": "nordeste_norte",
  "sousa": "nordeste_norte",
  "cajazeiras": "nordeste_norte",
  "guarabira": "nordeste_norte",
  "sapé": "nordeste_norte",
  "mamanguape": "nordeste_norte",
  "queimadas": "nordeste_norte",
  "monteiro": "nordeste_norte",
  "esperança": "nordeste_norte",
  "itabaiana pb": "nordeste_norte",
  "conde": "nordeste_norte",
  "jacumã": "nordeste_norte",
  "tambaba": "nordeste_norte",
  
  // ========== NORDESTE - ALAGOAS ==========
  "maceió": "nordeste_norte",
  "arapiraca": "nordeste_norte",
  "rio largo": "nordeste_norte",
  "palmeira dos índios": "nordeste_norte",
  "união dos palmares": "nordeste_norte",
  "penedo al": "nordeste_norte",
  "são miguel dos campos": "nordeste_norte",
  "santana do ipanema": "nordeste_norte",
  "delmiro gouveia": "nordeste_norte",
  "marechal deodoro": "nordeste_norte",
  "coruripe": "nordeste_norte",
  "murici": "nordeste_norte",
  "maragogi": "nordeste_norte",
  "barra de são miguel": "nordeste_norte",
  "japaratinga": "nordeste_norte",
  "são miguel dos milagres": "nordeste_norte",
  
  // ========== NORDESTE - SERGIPE ==========
  "aracaju": "nordeste_norte",
  "nossa senhora do socorro": "nordeste_norte",
  "lagarto": "nordeste_norte",
  "itabaiana se": "nordeste_norte",
  "são cristóvão": "nordeste_norte",
  "estância": "nordeste_norte",
  "tobias barreto": "nordeste_norte",
  "itabaianinha": "nordeste_norte",
  "simão dias": "nordeste_norte",
  "capela": "nordeste_norte",
  "propriá": "nordeste_norte",
  "barra dos coqueiros": "nordeste_norte",
  "canindé de são francisco": "nordeste_norte",
  "xingó": "nordeste_norte",
  
  // ========== NORDESTE - PIAUÍ ==========
  "teresina": "nordeste_norte",
  "parnaíba": "nordeste_norte",
  "picos": "nordeste_norte",
  "piripiri": "nordeste_norte",
  "floriano": "nordeste_norte",
  "campo maior": "nordeste_norte",
  "barras": "nordeste_norte",
  "uruçuí": "nordeste_norte",
  "corrente": "nordeste_norte",
  "são raimundo nonato": "nordeste_norte",
  "oeiras": "nordeste_norte",
  "pedro ii": "nordeste_norte",
  "luís correia": "nordeste_norte",
  "bom jesus": "nordeste_norte",
  "delta do parnaíba": "nordeste_norte",
  "serra da capivara": "nordeste_norte",
  
  // ========== NORDESTE - MARANHÃO ==========
  "são luís": "nordeste_norte",
  "imperatriz": "nordeste_norte",
  "são josé de ribamar": "nordeste_norte",
  "timon": "nordeste_norte",
  "caxias": "nordeste_norte",
  "codó": "nordeste_norte",
  "paço do lumiar": "nordeste_norte",
  "açailândia": "nordeste_norte",
  "bacabal": "nordeste_norte",
  "balsas": "nordeste_norte",
  "santa inês": "nordeste_norte",
  "chapadinha": "nordeste_norte",
  "pinheiro": "nordeste_norte",
  "itapecuru mirim": "nordeste_norte",
  "coroatá": "nordeste_norte",
  "viana ma": "nordeste_norte",
  "pedreiras": "nordeste_norte",
  "presidente dutra": "nordeste_norte",
  "grajaú": "nordeste_norte",
  "barreirinhas": "nordeste_norte",
  "lençóis maranhenses": "nordeste_norte",
  "alcântara": "nordeste_norte",
  "carolina": "nordeste_norte",
  
  // ========== NORTE - AMAZONAS ==========
  "manaus": "nordeste_norte",
  "parintins": "nordeste_norte",
  "itacoatiara": "nordeste_norte",
  "manacapuru": "nordeste_norte",
  "coari": "nordeste_norte",
  "tefé": "nordeste_norte",
  "tabatinga": "nordeste_norte",
  "maués": "nordeste_norte",
  "manicoré": "nordeste_norte",
  "humaitá": "nordeste_norte",
  "iranduba": "nordeste_norte",
  "são gabriel da cachoeira": "nordeste_norte",
  "autazes": "nordeste_norte",
  "presidente figueiredo": "nordeste_norte",
  "novo airão": "nordeste_norte",
  "barcelos": "nordeste_norte",
  
  // ========== NORTE - PARÁ ==========
  "belém": "nordeste_norte",
  "ananindeua": "nordeste_norte",
  "santarém": "nordeste_norte",
  "marabá": "nordeste_norte",
  "parauapebas": "nordeste_norte",
  "castanhal": "nordeste_norte",
  "abaetetuba": "nordeste_norte",
  "cametá": "nordeste_norte",
  "bragança": "nordeste_norte",
  "marituba": "nordeste_norte",
  "altamira": "nordeste_norte",
  "tucuruí": "nordeste_norte",
  "barcarena": "nordeste_norte",
  "tailândia": "nordeste_norte",
  "redenção": "nordeste_norte",
  "paragominas": "nordeste_norte",
  "capanema": "nordeste_norte",
  "itaituba": "nordeste_norte",
  "óbidos": "nordeste_norte",
  "monte alegre": "nordeste_norte",
  "breves": "nordeste_norte",
  "salinópolis": "nordeste_norte",
  "alter do chão": "nordeste_norte",
  "ilha de marajó": "nordeste_norte",
  "soure": "nordeste_norte",
  "salvaterra": "nordeste_norte",
  
  // ========== NORTE - TOCANTINS ==========
  "palmas": "nordeste_norte",
  "araguaína": "nordeste_norte",
  "gurupi": "nordeste_norte",
  "porto nacional": "nordeste_norte",
  "paraíso do tocantins": "nordeste_norte",
  "colinas do tocantins": "nordeste_norte",
  "guaraí": "nordeste_norte",
  "dianópolis": "nordeste_norte",
  "tocantinópolis": "nordeste_norte",
  "miracema do tocantins": "nordeste_norte",
  "arraias": "nordeste_norte",
  "jalapão": "nordeste_norte",
  "taquaruçu": "nordeste_norte",
  
  // ========== NORTE - RONDÔNIA ==========
  "porto velho": "nordeste_norte",
  "ji-paraná": "nordeste_norte",
  "ariquemes": "nordeste_norte",
  "vilhena": "nordeste_norte",
  "cacoal": "nordeste_norte",
  "rolim de moura": "nordeste_norte",
  "jaru": "nordeste_norte",
  "guajará-mirim": "nordeste_norte",
  "ouro preto do oeste": "nordeste_norte",
  "pimenta bueno": "nordeste_norte",
  "buritis": "nordeste_norte",
  "costa marques": "nordeste_norte",
  
  // ========== NORTE - ACRE ==========
  "rio branco": "nordeste_norte",
  "cruzeiro do sul": "nordeste_norte",
  "sena madureira": "nordeste_norte",
  "tarauacá": "nordeste_norte",
  "feijó": "nordeste_norte",
  "brasileia": "nordeste_norte",
  "epitaciolândia": "nordeste_norte",
  "xapuri": "nordeste_norte",
  "plácido de castro": "nordeste_norte",
  
  // ========== NORTE - RORAIMA ==========
  "boa vista": "nordeste_norte",
  "rorainópolis": "nordeste_norte",
  "caracaraí": "nordeste_norte",
  "alto alegre": "nordeste_norte",
  "mucajaí": "nordeste_norte",
  "pacaraima": "nordeste_norte",
  "cantá": "nordeste_norte",
  "bonfim": "nordeste_norte",
  "monte roraima": "nordeste_norte",
  
  // ========== NORTE - AMAPÁ ==========
  "macapá": "nordeste_norte",
  "santana": "nordeste_norte",
  "laranjal do jari": "nordeste_norte",
  "oiapoque": "nordeste_norte",
  "mazagão": "nordeste_norte",
  "porto grande": "nordeste_norte",
  "pedra branca do amapari": "nordeste_norte",
  
  // ========== ESPÍRITO SANTO (SUDESTE - TOM BALANCEADO) ==========
  "vitória": "sudeste_sp",
  "vila velha": "sudeste_sp",
  "serra": "sudeste_sp",
  "cariacica": "sudeste_sp",
  "cachoeiro de itapemirim": "sudeste_sp",
  "linhares": "sudeste_sp",
  "colatina": "sudeste_sp",
  "guarapari": "sudeste_sp",
  "são mateus": "sudeste_sp",
  "aracruz": "sudeste_sp",
  "viana es": "sudeste_sp",
  "domingos martins": "sudeste_sp",
  "santa teresa": "sudeste_sp",
  "alfredo chaves": "sudeste_sp",
  "anchieta": "sudeste_sp",
  "piúma": "sudeste_sp",
  "marataízes": "sudeste_sp",
  "itapemirim": "sudeste_sp",
  
  // ========== CENTRO-OESTE - GOIÁS ==========
  "goiânia": "sudeste_sp",
  "aparecida de goiânia": "sudeste_sp",
  "anápolis": "sudeste_sp",
  "rio verde": "sudeste_sp",
  "luziânia": "sudeste_sp",
  "águas lindas de goiás": "sudeste_sp",
  "valparaíso de goiás": "sudeste_sp",
  "trindade": "sudeste_sp",
  "formosa": "sudeste_sp",
  "senador canedo": "sudeste_sp",
  "novo gama": "sudeste_sp",
  "itumbiara": "sudeste_sp",
  "catalão": "sudeste_sp",
  "jataí": "sudeste_sp",
  "caldas novas": "sudeste_sp",
  "cidade de goiás": "sudeste_sp",
  "pirenópolis": "sudeste_sp",
  "alto paraíso de goiás": "sudeste_sp",
  "chapada dos veadeiros": "sudeste_sp",
  
  // ========== CENTRO-OESTE - MATO GROSSO ==========
  "cuiabá": "sudeste_sp",
  "várzea grande": "sudeste_sp",
  "rondonópolis": "sudeste_sp",
  "sinop": "sudeste_sp",
  "tangará da serra": "sudeste_sp",
  "cáceres": "sudeste_sp",
  "sorriso": "sudeste_sp",
  "lucas do rio verde": "sudeste_sp",
  "primavera do leste": "sudeste_sp",
  "barra do garças": "sudeste_sp",
  "alta floresta": "sudeste_sp",
  "pontes e lacerda": "sudeste_sp",
  "nova mutum": "sudeste_sp",
  "colíder": "sudeste_sp",
  "juína": "sudeste_sp",
  "poconé": "sudeste_sp",
  "chapada dos guimarães": "sudeste_sp",
  "nobres": "sudeste_sp",
  "bom jardim": "sudeste_sp",
  
  // ========== CENTRO-OESTE - MATO GROSSO DO SUL ==========
  "campo grande": "sudeste_sp",
  "dourados": "sudeste_sp",
  "três lagoas": "sudeste_sp",
  "corumbá": "sudeste_sp",
  "ponta porã": "sudeste_sp",
  "naviraí": "sudeste_sp",
  "nova andradina": "sudeste_sp",
  "aquidauana": "sudeste_sp",
  "maracaju": "sudeste_sp",
  "paranaíba": "sudeste_sp",
  "sidrolândia": "sudeste_sp",
  "coxim": "sudeste_sp",
  "jardim": "sudeste_sp",
  "miranda": "sudeste_sp",
  "bonito": "sudeste_sp",
  "rio verde de mato grosso": "sudeste_sp",
  "pantanal": "sudeste_sp",
  
  // ========== DISTRITO FEDERAL ==========
  "brasília": "sudeste_sp",
  "taguatinga": "sudeste_sp",
  "ceilândia": "sudeste_sp",
  "samambaia": "sudeste_sp",
  "plano piloto": "sudeste_sp",
  "gama": "sudeste_sp",
  "águas claras": "sudeste_sp",
  "recanto das emas": "sudeste_sp",
  "santa maria df": "sudeste_sp",
  "sobradinho": "sudeste_sp",
  "planaltina": "sudeste_sp",
  "guará": "sudeste_sp",
  "vicente pires": "sudeste_sp",
  "lago sul": "sudeste_sp",
  "lago norte": "sudeste_sp",
};

export function mapCityToRegion(city: string | null): BrazilRegion {
  if (!city) return "default";
  
  const normalized = city.toLowerCase().trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, ""); // Remove acentos para matching
  
  // Tenta match direto
  for (const [cityName, region] of Object.entries(cityRegionMap)) {
    const normalizedCity = cityName.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (normalized === normalizedCity || normalized.includes(normalizedCity)) {
      return region;
    }
  }
  
  return "default";
}

export function getRegionDisplayName(region: BrazilRegion): string {
  const names: Record<BrazilRegion, string> = {
    "sudeste_sp": "São Paulo",
    "sudeste_mg": "Minas Gerais",
    "sul": "Sul",
    "nordeste_norte": "Nordeste/Norte",
    "rio": "Rio de Janeiro",
    "default": "Brasil",
  };
  return names[region];
}

export function getRegionToneLabel(region: BrazilRegion): string {
  const tones: Record<BrazilRegion, string> = {
    "sudeste_sp": "Tom Direto",
    "sudeste_mg": "Tom Acolhedor",
    "sul": "Tom Formal",
    "nordeste_norte": "Tom Caloroso",
    "rio": "Tom Descontraído",
    "default": "Tom Padrão",
  };
  return tones[region];
}
